ktor {
    deployment {
        port = 8080
    }
    application {
        modules = [ com.fintech.server.ApplicationKt.module ]
    }
    auth {
        jwt {
            realm = "ktor"
            verifier {
                // Aquí se configurará el verifier de JWT
            }
        }
    }
}